version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli # Upgrade awscli
  build:
    commands:
      - npm install # Install package
      - npm test # Test package
      - npm prune --production # Remove devDependencies from package
      - chmod -R 777 * # Set 777 permissions for all files
      - zip -r impact-map.zip . # Zip current directory
      # Upload and replace Uri values in template
      - aws cloudformation package --template-file impact-map.yml --s3-bucket groundwire --s3-prefix impact-map --output-template-file impact-map-replaced.yml
artifacts:
  files:
    # Output the template with replaced values
    - 'impact-map-replaced.yml'
